version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: chat_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '${DATABASE_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: chat_web
    restart: always
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      - db
      - redis
      - elasticsearch

    environment:
      DATABASE_URL: '${DATABASE_URL}'
    volumes:
      - .:/rails

  sidekiq:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml -q message_creation -q chat_creation -q counters -q default
    container_name: chat_sidekiq
    restart: always
    depends_on:
      - db
      - redis
      - elasticsearch
    volumes:
      - .:/rails
    environment:
      DATABASE_URL: '${DATABASE_URL}'

  redis:
    image: redis:7
    container_name: chat_redis
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data

  elasticsearch:
    container_name: chat_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    # 8.x
    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    restart: always
    ports:
      - '${ELASTICSEARCH_PORT:-9200}:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: chat_kibana
    restart: always
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - '${KIBANA_PORT:-5601}:5601'

    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'

volumes:
  mysql_data:
  es_data:
  redis_data:
  kibana_data:
